# Generated by Django 5.0.1 on 2024-03-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendd', '0002_userregisterdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='donorregisterdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.EmailField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('confirmpassword', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('bloodgroup', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='picsss')),
            ],
        ),
        migrations.AlterField(
            model_name='userregisterdb',
            name='username',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
