# Generated by Django 5.0.1 on 2024-04-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendd', '0003_donorregisterdb_alter_userregisterdb_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='makerequestdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(blank=True, max_length=100, null=True)),
                ('patientage', models.IntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('bloodgroup', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
