# Generated by Django 5.0.1 on 2024-04-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendd', '0004_makerequestdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregisterdb',
            name='name',
        ),
        migrations.AlterField(
            model_name='userregisterdb',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
