# Generated by Django 5.0.1 on 2024-04-04 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontendd', '0005_remove_userregisterdb_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorregisterdb',
            name='name',
        ),
    ]
