# Generated by Django 5.0.1 on 2024-04-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendd', '0006_remove_donorregisterdb_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='donateblooddb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donorname', models.CharField(blank=True, max_length=100, null=True)),
                ('donorage', models.IntegerField(blank=True, null=True)),
                ('disease', models.CharField(blank=True, max_length=100, null=True)),
                ('bloodgroup', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
