# Generated by Django 5.0.1 on 2024-04-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendd', '0007_donateblooddb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateblooddb',
            name='unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
