# Generated by Django 5.0.1 on 2024-04-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendd', '0008_alter_donateblooddb_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makerequestdb',
            name='unit',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
