# Generated by Django 5.0.1 on 2024-04-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendd', '0009_alter_makerequestdb_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='donateblooddb',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
