# Generated by Django 5.0.1 on 2024-04-08 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontendd', '0010_donateblooddb_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donateblooddb',
            name='status',
        ),
    ]
