# Generated by Django 5.0.1 on 2024-01-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donordb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('Bloodgroup', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Contact', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
